provide_settings:
  llm:
    provider: "Ollama"
    config:
      model: "deepseek-r1:1.5b"

  embedding:
    provider: "OllamaEmbedding"
    config:
      model: "deepseek-r1:1.5b"
      dimension: "1024"

  file_loader:
    provider: "TextLoader"
    config: {}

  web_crawler:
    provider: "FireCrawlCrawler"
    config: {}

  vector_db:
    provider: "Milvus"
    config:
      default_collection: "deepsearcher"
      uri: "/root/.ollama/milvus.db"
      token: "root:Milvus"
      db: "default"

query_settings:
  max_iter: 3

load_settings:
  chunk_size: 1500
  chunk_overlap: 100