# disableContainerInterface disables IPAM, so not for pods
# macspoofchk requires `nft`, stuck on adding cluster NIC
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: pod-bridge
spec:
  config: '{
      "cniVersion": "1.0.0",
      "name": "bridge",
      "type": "bridge",
      "bridge": "kvm0",
      "ipam": {
        "type": "dhcp",
        "daemonSocketPath": "/run/cni/dhcp.sock"
      }
    }'
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: vm-bridge
spec:
  config: '{
      "cniVersion": "1.0.0",
      "name": "bridge",
      "type": "bridge",
      "bridge": "kvm0",
      "ipam": {
        "type": "dhcp",
        "daemonSocketPath": "/run/cni/dhcp.sock"
      }
    }'
# https://github.com/k8snetworkplumbingwg/multus-cni/blob/2ecd4f4b47b7821c7a65fac940dc5327bb4c5be8/pkg/k8sclient/k8sclient.go#L710
# The CRD object of default network should only be defined in multusNamespace