# kubectl virt image-upload dv debian13 --insecure --size=128Gi --access-mode=ReadWriteOnce --force-bind --uploadproxy-url=https://192.168.0.102:8443 --image-path=debian13.qcow2

apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: cdi-uploadproxy
  namespace: cdi
spec:
  routes:
  - match: HostSNI(`cdi-uploadproxy.magicloud.lan`)
    services:
    - name: cdi-uploadproxy
      port: 443
  tls:
    passthrough: true
---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: cdi-uploadproxy
  namespace: cdi
spec:
  endpoints:
    - dnsName: cdi-uploadproxy.magicloud.lan
      recordType: A
      targets:
        - 192.168.0.102
---
apiVersion: v1
kind: Service
metadata:
  name: cdi-uploadproxy-out
  namespace: cdi
spec:
  ports:
  - port: 8443
    protocol: TCP
    targetPort: 8443
  selector:
    cdi.kubevirt.io: cdi-uploadproxy
  type: LoadBalancer