apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: debian13
spec:
  runStrategy: Always
  template:
    spec:
      domain:
        cpu:
          cores: 2
        # guest memory defaultly equal to this
        resources:
          requests:
            memory: 4G
        devices:
          disks:
            - name: disk0
              disk:
                bus: virtio
          interfaces:
          - name: pod
            bridge: {}
      networks:
      - name: pod
        pod: {}
      volumes:
        - name: disk0
          persistentVolumeClaim:
            claimName: debian13
