---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mqtt-cred
  namespace: nvr
spec:
  encryptedData:
    FRIGATE_mqtt_password: AgDD/pfaDGufFPa2+bimgifAeHF1sYTfmZQs1AQZRYlNiuogKIq5VZK9QWsh/RCJo38g4ta5F0CL4fpmK2QoR1Mo/ZugiEHn5a+xFTHobnwerIr8dv28zJ1xCernH/VQhB7Sx1COQXer+Uic6Vy9KFs3csUJLet8hAKpJeXsKO64aqYkNTLJNpBUgs1utzTw0INSK4dYDQPQ5amL7uHc4H69hHHcSUXTb4ddcokLwOEIddEvRlp3sniVGWod3miRSsAnSdRmLS5/q3CeutV4UIaf9FOpP6PQvF6E68jPqMWocd/ZURg16zebAEQ5cJ+PcKgu2viQs0J+ZSvJoM8o/6StwbOX8606CR7Cdo97/90jkYM3xXNtyn9WDZxMNu7erf/AIl2+rq5PC7WHGig26NdXbFgqfGv1DMdCnbNkNu/XAj+Dz7kxjxpljQDN0M7Y0IYTQe1bTI1+wwQ3aUgSm/eVYNpGabt8XvIRI01BT+oRfROrsZQZxF7gcknsXCqz5RsSKv3XBJTwzeUszamsjstuR69Tx3a3bwcyplI1riQNAES2fy7wcL+wuiap7rklut9B1lyafkEnMXSGMVjZHrj3NuMmg6rHbWHGGEQat/g4NON5qMRObXOBGJ1nZPewUaMzkjkOvLETCzYYeo4ztf16xEvY14RcwmNIhlUsXB3zw0IgjMLI4UH5+Cq9J0mECJPV6BMn
    FRIGATE_mqtt_username: AgDAtvlDuMK/M+QyVcemLgNx/jQmUoXU06f5fcdphLSCd2Oygcx5X09Ib6KKuWBWq/XwoNdfCS82T8YI7YVkvkJ4LWZydGPI5IseGTVLzSYJFaRQXjpB6PEFy6Se3P9qp4t4t8bounFkidjwEJYTVJ5fL+nmgajyOrV8Bhu1dB0sqmsLDCceTEhSkiLsrg2JcZkeOP3GgHkk1ahkWyMQcWGx3Cc8m+7csApByAMEAEQKP/ScuQR1d0R+4KsbJ1KRHKWi3qhR+xuJDenbwMIzIgqkL6ghG+rZiSOU0WkuUyKGlrNBNbSd8968NfkqiZ37qH29N+fMi4GCWqiWZ1TGT+EFwKxoPuu93RkUfS9frV6FJv+jo1IeQe8IcJ3eTBzRATKnkXTUq2sZBopDf06JYtqB0n9jp9sG5jgaZ6lv7hZF/VbNaNcSH+/Lgcx1V0WzBygL6skcUPsBHtNbmvMgu3GxRyREIDhUOVW3qwompZ0ZdjNQRXGxA8ceg8tK+R9w/ez5bEz3yAGMBD7yjAbRmrTIS7QQbCODc8slPPrfxZSZrzjtUtkksxoYxiT3LcCXyLQRLmIAdABxHB74cIrr1be4udFkThkIoLHCczwCSYRkHVv92ZcYmSsHMwzP3gNxnniszy2gM2wTHCzaqdmb6Q7gegLFAHq3g73G89urnD86+gkZZFyDZr8PQhrli9mXent/aaHj
  template:
    metadata:
      creationTimestamp: null
      name: mqtt-cred
      namespace: nvr
    type: Opaque
