---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: v2ray
spec:
  replicas: 1
  selector:
    matchLabels:
      app: v2ray
  template:
    metadata:
      labels:
        app: v2ray
    spec:
      volumes:
      - name: config-json
        configMap:
          name: config-json
      containers:
      - name: v2ray
        image: v2fly/v2fly-core:latest
        args:
        - run
        - -c
        - /config-json/config.json
        volumeMounts:
        - name: config-json
          mountPath: /config-json
          readOnly: true
        ports:
        - name: v2ray
          containerPort: 2080
---
apiVersion: v1
kind: Service
metadata:
  name: v2ray
spec:
  type: LoadBalancer
  selector:
    app: v2ray
  ports:
    - port: 2080
      targetPort: v2ray
