step-certificates:
  enabled: false

ca:
  url: "https://step-certificates.default.svc.cluster.local"
  provisioner:
    name: "magicloud@magicloud.lan"
    password: "ZZYI3hQ0LdJh33KHKR3ywScZxG1FFPNl"
  certs:
    root_ca.crt: |-
      -----BEGIN CERTIFICATE-----
      MIIBpDCCAUqgAwIBAgIRAL9mLMVzW1+sNJlLYgcxa7QwCgYIKoZIzj0EAwIwMDES
      MBAGA1UEChMJTWFnaWNsb3VkMRowGAYDVQQDExFNYWdpY2xvdWQgUm9vdCBDQTAe
      Fw0yNTEwMTkxMTMxMjZaFw0zNTEwMTcxMTMxMjZaMDAxEjAQBgNVBAoTCU1hZ2lj
      bG91ZDEaMBgGA1UEAxMRTWFnaWNsb3VkIFJvb3QgQ0EwWTATBgcqhkjOPQIBBggq
      hkjOPQMBBwNCAATqT1b5TpK9QKg/rvgdDPA7ZvKEjD+TZcm5MDicyzpchrvUSYnl
      +p8ZiET/7GJzRtNCA5LAI1/R5Pg4P37nzHpio0UwQzAOBgNVHQ8BAf8EBAMCAQYw
      EgYDVR0TAQH/BAgwBgEB/wIBATAdBgNVHQ4EFgQUS2oQLeQ2yFgiUU1n0IkDdBwY
      rhIwCgYIKoZIzj0EAwIDSAAwRQIhAPtWHa1Ehusmdhdx0YRsiTFIMjeOYtYj+NWb
      Y9c6x4QbAiADjI5OcxYvCjxTwqMDFSpqW8EARAep+lQNLCS6sOeTRQ==
      -----END CERTIFICATE-----
